### ISSUE TITLE
Readme license is incompatible with LICENSE

### ISSUE THREAD

**Issue by danbopes** [SOBotics/SpotDetector#3]
SpotDetector is licensed under "GNU General Public License v3.0"

The readme refers to "GNU General Public License v3.0 **or later**", which is not compatible. Please update the readme to use the correct license: https://spdx.org/licenses/GPL-3.0-only.html or simply link them to the [github license](https://github.com/SOBotics/SpotDetector/blob/master/LICENSE) page which already displays a wonderful explanation at the top.

**Comment by Oaphi** [comment]
@danbopes done, sorry, copy-pasting error!
